CREATE TABLE HEROES (
	ID INT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	IMG_URL VARCHAR(100) NULL,
	INTELLIGENCE INT NOT NULL,
	SPEED INT NOT NULL,
	COMBAT INT NOT NULL
);

CREATE SEQUENCE "HEROES_SEQ"
MINVALUE 731
MAXVALUE 999999999
INCREMENT BY 1
START WITH 731
NOCACHE
NOCYCLE;